### ISSUE TITLE
Organize GitHub issues in preparation for possible "Hack The Left: An Anticapitalist Hackathon" participants

### ISSUE THREAD

**Issue by meitar** [meitar/better-angels#124]
@unquietpirate, would you be able to please help me organize this repository's issues before [Hack The Left](https://noisebridge.net/wiki/HackTheLeft) starts so that, in case someone at that event wants to help us out, they will have an easy way to navigate the now more than one hundred tickets in this issue tracker? Also, this would help me get a better view of what's currently documented in our issues, too.

Here's what I'm thinking.

The main thing that needs doing is [creating and editing labels](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/) for the issues that already exist so that they are more easily browsable. What do you think of the following approach:

* Create labels that refer to **skills** needed to accomplish some task, and apply this label to the appropriate issues. For instance, #48 ("integrate with push-to-talk functionality") might be labelled "`skill:Android programming`" because it requires knowing how to do Android programming to accomplish.
* Create labels that refer to major **components** of Buoy itself. We already have a [component:notifications](https://github.com/meitar/better-angels/issues?utf8=%E2%9C%93&q=label%3Acomponent%3Anotifications) label. We should probably also have labels like `component:teams`, `component:chat`, and other kinds of "`component:*`" labels.
* Create labels that refer to the estimated **difficulty** to accomplish a task.
 * Or, alternatively, create a special label for "low-hanging fruit" that we estimate to be particularly easy, simple, or approachable for non-technical users. Then find any issues that are easy, or add a bunch of new issues that are easy (for example, fixing the documentation in [the various `help` files](https://github.com/meitar/better-angels/tree/master/help#readme) does not require coding skill at all), and then tagging those issues with this special "low-hanging fruit" label. Maybe we could call it "`good first issue`" or something? (This is modeled after [WordPress Core's workflow keywords](https://make.wordpress.org/core/handbook/contribute/trac/keywords/) idea.)

We already have some more general labels for these things, like `help wanted`, which I currently use to indicate a general "hey, I'd like it if someone chimed in on this, please," but the repository is not currently set up to efficiently triage a lot of new contributors at once.

/cc @hannahhubbard, @nitishnarula

**Comment by meitar** [comment]
(Currently only a couple people have access to edit labels, but if someone not listed above wants to take this task on, I am happy to add you as a collaborator so that you, too, can help organize this growing issue list. Thanks)

**Comment by unquietpirate** [comment]
Good idea. I've started working on this. I'm currently focusing on adding component:* labels to as many issues as makes sense. 

I also added the "security" label to several issues such as #118, #111, and #110 -- but had second thoughts, because I'm not sure if I'm using the "security" label correctly. I also created a "privacy" label (but have so far only used it on #110 because that issue uses the term 'privacy' explicitly.) 

In terms of organizing development, does it make sense to bundle all of these and related issues together, or is there a subtle distinction between "security" and "privacy" that I should be distinguishing? Thoughts? 

Thanks for this suggestion. I think it will help me organize my own thinking about the currently existing and future components of Buoy, also. :)

**Comment by meitar** [comment]
> In terms of organizing development, does it make sense to bundle all of these and related issues together, or is there a subtle distinction between "security" and "privacy" that I should be distinguishing? Thoughts?

Y'know, that's a good question. "Security" is nebulous, and I've been using it primarily to identify what I have identified as things that the "computer security industry" would classify as an exploit potential. Ideally, this sort of thing would be disclosed to me privately, and not be discussed on these forums until the issue can be patched. So, given that, such issues wouldn't even *have* a label, and therefore I don't know if labeling others `security` really warrant that distinction.

Ultimately, I think you're doing just fine and if something like this is unclear it's because it's legit ill-defined, not because you're missing some information you need. That gives you the de-facto authority to define it as you wish. Set up a wiki page for "labels" or something to formally define anything you need and we can hash things out if we need to when there is either further clarifying information available or a limitation in our workflow becomes clearer.

And thanks!!

**Comment by unquietpirate** [comment]
Okay! Thanks. :)

For the time being, I think I'm going to use the "Privacy" label to tag issues that strike me as specifically relevant to user privacy and leave the "Security" label alone -- since, at least at this stage of development, it does seem useful to be able to tag issues related to exploit potential here, but I don't personally know much about what the "computer security industry" would deem as such.

**Comment by meitar** [comment]
:+1: Yeah, that sounds good to me.

**Comment by meitar** [comment]
Nice job, this looks done. This is the only issue without labels. :)
