### ISSUE TITLE
WordPress plugins, including SEO, are visible to Buoy users

### ISSUE THREAD

**Issue by TechForJustice** [meitar/better-angels#146]
Tech for Justice's SEO plugin is visible on the WordPress homepage. Organizations may not want Buoy users to have access to that data.

![picture1](https://cloud.githubusercontent.com/assets/11147797/12969634/c93d756a-d048-11e5-8042-59350b9a7d0f.png)

**Comment by meitar** [comment]
This has nothing to do with Buoy, [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/) is a completely different plugin.

**Comment by christyleos** [comment]
Understood; is there anyway to restrict what the Buoy users see on the dashboard? I think this is a valid question since we are basically telling organizations that we want them to grant website access to users. If an organization comes along and finds out that Buoy users can see their other plugins that could be a problem. Unless this is a simple issue to fix; in that case I can send something to our tech writer to make a note of it.

**Comment by nitishnarula** [comment]
This has more to do with Wordpress than Buoy. Buoy users can only see admin restricted information (like the plugins page) if their role gives them this access. If on your wordpress website Buoy users are being added as anything other than "Subscriber" role then they might have access to such information. See Wordpress Settings -> General.

**Comment by meitar** [comment]
On a default WordPress installation, new users are registered as Subscribers. This means they only have `read` capabilities. There's nothing more they need to use Buoy. The plugin already handles all required permission checks itself and does not grant extra capabilities to any user.

Since you have a WordPress website, why don't you try this out for yourself?
