### ISSUE TITLE
Privacy Feature Request: When inviting Team Members by e-mail address, user should always receive same response

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#56]
I wasn't entirely sure how to phrase the title, so hopefully this will make sense.

Currently, when I invite a user to join My Team by entering their e-mail address in the "Add a team member" field, I get one of two responses: If the e-mail is associated with an existing Buoy account, that account's username automatically appears as "pending" in my team member list. If I send an invitation to an e-mail that does not have an associated account, I receive a message stating "You have invited yourname@example.com to join this Buoy site, but they are not yet on your response team. Contact them privately (such as by phone or txt) to make sure they created an account. Then come back here and add them again."

It could enhance the privacy of users if, when I invite someone to join my team via e-mail address, I always receive the second response -- even if that e-mail address is associated with an existing account. This protects against the case where an abusive user is plugging in the e-mails of people they know in order to determine if a particular person is a Buoy user. In other words, a user who is invited by e-mail does not only have to approve the Join My Team request, they also have to approve the invitation-sender knowing of their account on the site.

Is this overkill?

**Comment by meitar** [comment]
Not overkill. #34 arguably introduces an email enumeration attack that could result in unauthorized information disclosure. But theb again, so does WordPress itself. For example, say I want to know if you have an account on a specific WordPress website but I don't want to ask you. How can I find out? Well, if I know your email address, then I can simply try registering for a new account with that email address. If I get an error from WordPress like this:

> ERROR: This email is already registered, please choose another one.

theb I know you've got an account on that site.

Is this a problem? Depends. I'm sure it's better not to reveal that information than it is to reveal that information in a hostile use case like DV, but how do we account for WordPress's own behavior?

This issue is mitigated somewhat by the fact that Buoy is somewhat less centralized than people really seem to understand. For an attacker to discover that you use Buoy, they have to know your email address *and* they have to know which Buoy server you use. This is the same as with email: they have to know your email username *and* the domain of that email service.

Since fixing this "privacy leak" in our own plugin code does nothing to fix the same exact issue in the WordPress core, I'm going to close this and mark wontfix for now.
